### ISSUE TITLE
Extract MVP components from datapackage-ui

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/tableschema-ui#1]
# Description

We want to allow users to create, edit and validate Table Schemas from a web interface.

We have an earlier version of a similar library [here](http://datapackagist.openknowledge.io), for Data Packages. While we consider this implementation to be a bit flawed, it does show all the moving parts and useful implementation approaches for building out `tableschema-ui`.

The most important component is the use of [json-editor](https://github.com/jdorn/json-editor) to generate web forms out of JSON Schema files.

# Tasks

- [ ] Farm out from https://github.com/frictionlessdata/datapackage-ui
- [ ] Create a new Table Schema
- [ ] Edit an existing Table Schema
- [ ] Validate a Table Schema
- [ ] Download as a `tableschema.json` descriptor
- [ ] Tests

**Comment by pwalsh** [comment]
@roll there is no *requirement* to use JSON Editor - the new UI is quite different from a normal form, and JSON Editor is designed around auto-generating "normal" web forms.

**Comment by roll** [comment]
@pwalsh 
I think It's better to close this repo (at least on this stage) and do all the work in `datapackage-ui` repo. It will save a lot of time on syncing between repos and of other overhead. For users it will be the same instead of `tableschemaUI.EditorSchema` there will be `datapackageUI.EditorSchema`.

**Comment by roll** [comment]
https://github.com/frictionlessdata/datapackage-ui/issues/234

**Comment by roll** [comment]
MOVED (at least for now on the prototype stage)
https://github.com/frictionlessdata/datapackage-ui/issues/234
