### ISSUE TITLE
Initial implementation focused on CKAN integration

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-ui#2]
# Overview
See https://github.com/frictionlessdata/ckanext-validation/pull/25

# Tasks

- [x] bootstrap the app
- [x] implement black-box stub
- [x] fix coverage/reloading
- [x] implement `details` section
- [x] add title/description editing
- [x] do we need the `save` button? - no
- [x] proper type/format selection
- [ ] ---
- [x] don't lose metadata (missingValues etc)
- [x] show column sample for every field
- [x] support File API uploads
- [ ] ---
- [x] fix type/format for uploaded schemas
- [x] warn if data not provided - no
- [x] add `createColumn` helper
- [x] warn if validation error - no (sever side)
- [x] add `input.pattern` - no application
- [x] tabs `fields/editor`?
- [x] remove no fields error
- [ ] ---
- [x] rebase on modal
- [x] handle multiple `Edit` call
- [x] aligh `details/remove` buttons
- [x] handle loading errors
- [x] name/type/format width on mobiles
- [x] implement disposing component
- [x] add `first 10 rows` note
- [x] inner components no names issue
- [x] limit count of rows to load for source 
- [x] publish demo
- [ ] ---
- [x] fix production version (csvSniffer bug)
- [x] use the bootstrap version ckan uses
- [x] improve savedSchema/dispose logic
- [x] integrate into ckan-validation
- [ ] ---
- [x] suport field sorting? - no 
- [x] fix details/remove on 1300px screen (use font awasome?)
- [x] provide initial `loading` indicator
- [x] update readme
- [ ] ---
- [x] fix loading big files speed - MOVED #3
- [x] fix all ckan integation issues
- [x] sync demo with ckan
- [x] use `tableschema@1.10.0`
- [x] test for defective csv input
- [x] fix bug  on `defective-rows.csv` file
- [x] allow to start from scratch if there is an error
- [x] infer only for csv format files
- [x] allow to disable preview
- [ ] ---
- [x] recover karma testing?
- [x] write required tests
- [x] ensure that big files works -> #6
- [ ] ---
- [x] release the component

**Comment by roll** [comment]
DONE
